FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY consumer.py .
# We use -u to force unbuffered logs so you see them in Docker immediately
CMD ["python", "-u", "consumer.py"]